### ISSUE TITLE
🪲 Parquet Files (probably others) inner joined on themselves miss columns

### ISSUE THREAD

**Issue by gva-jjoyce** [mabel-dev/opteryx#1007]
May be resolved by #481

~~~sql
SELECT * FROM file INNER JOIN (SELECT id FROM file) USING (id)
~~~

returns two `id` columns, regardless of the content of the file

**Comment by joocer** [comment]
Won't be solved by that issue.

Appears that the code to prevent projection when `*` is in the query is being ignored. Probably not related to the table self-joining.
