### ISSUE TITLE
✨ Push & Order Predicates

### ISSUE THREAD

**Issue by joocer** [mabel-dev/opteryx#1277]
Push predicates to scans, either into the scan themselves (Parquet, SQL and Collections) or straight after the scan (move the filter node)

Order adjacent nodes so that binary ops (equals, not equals, greater than etc) are put before anything else. This may not be optimal all of the time, but should be better than random ordering most of the time.

**Comment by joocer** [comment]
I order the predicates as a starting point - I need to collect them and push them to the appropriate join or scan

**Comment by joocer** [comment]
Predicates pushed closer to reads but not into reads.
Predicates pushed into JOINs, including rewriting CROSS and INNER joins

**Comment by joocer** [comment]
- [ ] push eqi filters into firestore
- [ ] push limited filters into parquet
- [ ] push most filters into SQL

**Comment by nico525** [comment]
Hi joccer, for this and the query rewriting I would suggest looking into SQLGlot and especially the rules which rewrite the queries

**Comment by joocer** [comment]
> Hi joccer, for this and the query rewriting I would suggest looking into SQLGlot and especially the rules which rewrite the queries

G'day @nico525 , thanks for your interest and thank you for the suggestion. I've looked at SQLGlot before, it's a great project and I've contributed features to it in the past. After a review and a proof-of-value integration, I decided Opteryx would ultimately benefit more from its own planning libraries.

**Comment by nico525** [comment]
I see, but in my opinion utilizing the ruleset should be a viable option

**Comment by joocer** [comment]
> I see, but in my opinion utilizing the ruleset should be a viable option


Thanks again for your input. It's great to have this dialogue with someone who appreciates the nuances of SQL query processing tools. 

SQLGlot is awesome for working between different SQL dialogues, and last time I reviewed the code it had a solid rules-based query optimizer.


Opteryx will be implementing a similar set of optimizations, and some of the ground work for cost-based optimizer is being put in place. Opteryx has specific needs for its optimizers that would mean additional optimization strategies would be needed and a translation layer was going to be needed to integrate with the Opteryx execution engine.

I appreciate your enthusiasm for SQL query tools. It’s clear that you have a keen interest in the field. Opteryx, while having some similarities with SQLGlot, is primarily a query federation tool. It’s designed to act as a single interface for querying across a variety of data and storage systems, which is a bit different from SQLGlot's language unification approach. One is like a universal translator, and the other is like a switchboard.

Thanks for the engaging conversation, Nico. Your interest in these tools is really appreciated.

**Comment by joocer** [comment]
Rather than trying to build a second tree for predicate push down, we can use the graph maintenance functions of remove and insert. We will always be removing predicates as we collect them, inserting to execute just after scans etc, or inserting then just before the last exit if we don't know where else to put it.

**Comment by joocer** [comment]
Implemented for file/blob-based scanners and the SQL scanner, dealing with bugs and edge-cases.
