### ISSUE TITLE
[BUG]  Field X does not exist in table schema

### ISSUE THREAD

**Issue by joocer** [mabel-dev/opteryx#171]
This was the same query that failed - but this one works

~~~sql
SELECT COUNT(*), planetId 
FROM $satellites
FOR TODAY
GROUP BY planetId
ORDER BY COUNT(*) DESC
LIMIT 10
~~~

On the 'live' query - removing the `ORDER BY` clause, the error no longer occurs

**Comment by gva-jjoyce** [comment]
See bug #179 , given the example uses a GROUP BY, it's the likely cause.
