### ISSUE TITLE
[BUG] Aggregate Node creates new metadata for each chunk

### ISSUE THREAD

**Issue by gva-jjoyce** [mabel-dev/opteryx#179]
**Describe the bug**
Anything that processes results from a GROUP BY that goes across pages will have an inconsistent set of columns because the aggregate node creates new metadata for each page, see line 271.

This can be seen in queries which SELECT, WHERE or otherwise access columns what are the result of a GROUP BY.

To resolve, the metadata should be created one and saved to each page, similar to the mechanism used in the blob reader.

**Comment by joocer** [comment]
can replicate with new (unreleased) `FAKE` constructor

~~~sql
SELECT count(*), column_1 FROM FAKE(10000,2) GROUP BY column_1 ORDER BY COUNT(*)
~~~
