### ISSUE TITLE
[FEATURE] When reporting that a column doesn't exist, it should suggest likely correct columns

### ISSUE THREAD

**Issue by gva-jjoyce** [mabel-dev/opteryx#203]
Using something like levenshtein distance to find likely corrections for typos, column not found should say something like "Column 'firstname' not found, you may have meant 'first_name'"

**Comment by joocer** [comment]
This would likely be a feature of the Columns class, a `fuzzy_search` to find approximate matches.

This should use metaphone and levenshtien.
