### ISSUE TITLE
🪲TypeError: expected string or bytes-like object, got 'ArgumentInfo'

### ISSUE THREAD

**Issue by cliveeisen** [mabel-dev/opteryx#2091]
### Thank you for taking the time to report a problem with Opteryx.

Debian GNU/Linux 12 (bookworm)

I am sure this is PEBCAK but following the command line example of
opteryx --read_2024-11-01.parquet "select * from 'read_2024-11-01.csv';" 

I get 

Traceback (most recent call last):
  File "/root/.local/bin/opteryx", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.local/pipx/venvs/opteryx/lib/python3.11/site-packages/opteryx/__main__.py", line 144, in main
    sql = clean_statement(remove_comments(sql))
                          ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/opteryx/lib/python3.11/site-packages/opteryx/utils/sql.py", line 28, in remove_comments
    return regex.sub(_replacer, string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'ArgumentInfo'

in fact whatever I pass on the command line I get this sort of error

**Comment by joocer** [comment]
Hi @cliveeisen - Thank you for reporting this issue with Opteryx. It appears there may be a problem with the CLI interface in handling command-line arguments.

We’re able to replicate the issue, so we’re prioritizing it as a bug and will be investigating a fix. If you need assistance with specific queries or workarounds in the meantime, please let us know. Thanks again for helping us improve Opteryx.

**Comment by joocer** [comment]
@cliveeisen, I've created a test release to address this bug:

`pip install opteryx==0.18.2b854`

From the command in the issue, I think you were trying to query a CSV file and save the result to a Parquet file - this would be the syntax to do that

`opteryx --o read_2024-11-01.parquet "select * from 'read_2024-11-01.csv';"`
