### ISSUE TITLE
🪲 Key Error when including aggregate in inline function

### ISSUE THREAD

**Issue by gva-jjoyce** [mabel-dev/opteryx#505]
**Describe the bug**

**SQL statement**
Please submit the SQL statement, or a representative example using the sample datasets.
~~~sql
SELECT name, COUNT(*) * -1
  FROM $planets
GROUP BY name
ORDER BY COUNT(*) DESC
~~~

**Expected behaviour**

**Additional context**

**Comment by joocer** [comment]
problem was that `COUNT(*)` doesn't exist, it's `COUNT(*)*-1`, error trapped and improved
