### ISSUE TITLE
✨New Optimizations

### ISSUE THREAD

**Issue by joocer** [mabel-dev/opteryx#764]
**heuristic**

- [ ] Remove subqueries that don't do anything `SELECT * FROM (SELECT * FROM table)` - do this after CTEs have been added. [see this documentation](https://dev.mysql.com/doc/refman/8.0/en/derived-table-optimization.html)
- [ ] Embed CTE into plans (CTEs are implemented as reusable subqueries)
- [ ] Remove `LEFT/RIGHT JOIN` on a relation with no duplicates [see this implementation](https://github.com/tobymao/sqlglot/blob/main/sqlglot/optimizer/eliminate_joins.py)
- [ ] `(x AND y) OR z` -> `(x OR z) AND (y OR z)`, to allow splitting and pushing
- [ ] `(x AND y) OR (y AND z)` -> `(x OR y) AND (x OR z) AND (y OR y) AND (y OR z)` to allow splitting and pushing
- [ ] Remove `CROSS JOIN`
- [ ] `A AND (A OR B)` -> `A`
- [ ] `A OR (A AND B)` -> `A`
- [ ] `A AND (NOT A OR B)` -> `A AND B`
- [ ] `A OR (NOT A AND B)` -> `A OR B`
- [ ] `(A AND B) OR (A AND NOT B)` -> `A`
- [ ] `(A OR B) AND (A OR NOT B)` -> `A`
- [ ] Push `LIMIT` as far down tree as possible (to pipeline breakers/scanners), including support in readers

**catalogue-based**

- [ ] Remove redundant `CASTS` (casting a value to a compatible type)
- [ ] When we have a join between columns, add and push predicates to filter the reads to the range of the joined column, e.g. `JOIN ON x.a = y.b`, if x.a is always greater than 10 and y.b is not, push a predicate when reading y to prefilter anything less than 10.

**cost-based**

- [ ] order filters based on likely lowest cost (simulate combinations) - e.g. filtering 99% with an expensive filter may be slower than filtering 50% with a fast filter so fewer are processed by the slow filter.

**Comment by tobymao** [comment]
I'm wondering if you're interested in just using SQLGlot for parsing and optimization?

**Comment by joocer** [comment]
Thanks @tobymao,
 
Your project is awesome, I tried writing a SQL parser from scratch and realized I should find something that has already solved that problem.

It was a decision between SQLGlot and sqloxide/sqlparser-rs, but it was the speed that eventually led me to try sqloxide first. sqloxide doesn't appear to be kept in lock-step with sqlparser-rs so I have a fork, I don't push these back to Will's repo as they'd pretty much be the same as the Dependabot PRs. I'm reasonably happy with sqlparser-rs as a parser. 

I don't recall SQLGlot having an optimizer, I wonder if it's practical to incorporate SQLGlot as a SQL rewriting optimizer, and then use the existing parser/optimizer for cost and catalogue-based optimizations.

**Comment by tobymao** [comment]
Definitely, you can do further physical / statistical optimizations in your own planner, but leverage SQLGlot as a first pass.
