### ISSUE TITLE
✨ Review use of SQLGlot as SQL Rewriter

### ISSUE THREAD

**Issue by joocer** [mabel-dev/opteryx#768]
CF #764 

[SQLGlot](https://github.com/tobymao/sqlglot) includes a number of heuristic-based optimizations, investigate using SQLGlot to do an initial parse and optimize of provided statements and then output the resultant SQL for parsing in sqlparser-rs.

Some gotchas anticipated are:

- Handling of parameter substitutions
- Non-standard syntax handling
- Some optimizations may not be suitable for this specific use-case (e.g. the way selection and projection pushdowns work)
- non SELECT queries

These are either not mentioned in the documentation reviewed so far or appear opinionated in the documentation.

Some advantages are:

- We can push some optimizations written in Opteryx but aren't in SQLGlot (e.g. negative eliminations) and be good open source citizens
- New optimizations will be added by a larger community rather than all hand-coded by Opteryx developers

First step is to add SQLGlot as an impotent step in the execution flow (get SG to parse everything in the regression suite and see what happens).

Depending on the outcome, either

- back out
- try parsing back to raw SQL and running through
- submit fixes to SG

**Comment by joocer** [comment]
**SQLGlot Parsing Failures**

~~~sql
SELECT * FROM $satellites WHERE `name` = 'Calypso'
~~~
~~~sql
SELECT * FROM `$satellites` WHERE name = 'Calypso'
~~~
~~~sql
SELECT * FROM $satellites WITH (NO_CACHE)
~~~
~~~sql
SELECT * FROM $satellites WHERE name ~ '^C.'
~~~
~~~sql
SELECT * FROM $satellites WHERE name !~ '^C.'
~~~
~~~sql
SELECT * FROM $satellites WHERE name ~* '^c.'
~~~
~~~sql
SELECT * FROM $satellites WHERE name !~* '^c.'
~~~
~~~sql
SELECT * FROM UNNEST(('foo', 'bar', 'baz', 'qux', 'corge', 'garply', 'waldo', 'fred')) WHERE unnest LIKE '%e%'
~~~
~~~sql
SELECT GREATEST ( LIST ( name ) ) as NAMES FROM $satellites GROUP BY planetId
~~~
~~~sql
SELECT LEAST ( LIST ( name ) ) as NAMES FROM $satellites GROUP BY planetId
~~~
~~~
SELECT INTERVAL '1 1' DAY TO HOUR
~~~
~~~
SELECT * FROM $astronauts WHERE 'Apollo 11' IN missions
~~~
~~~sql
SELECT * EXCEPT id FROM $satellites

**Comment by tobymao** [comment]
it's easy to fix the $ by mapping it to a parameter, you can also do that in your own custom dialect. 

class CustomDialect(Dialect):
    Tokenizer(Tokenizer):
        KEYWORDS = {
           "$": TokenType.PARAMETER
...

**Comment by tobymao** [comment]
this doesn't fail for me

```python -m sqlglot "select * from testdata.nulls WHERE tweet ILIKE '%TRUMP%'"
SELECT
  *
FROM "testdata"."nulls"
WHERE
  "tweet" ILIKE '%TRUMP%'
```

**Comment by tobymao** [comment]
it should be easy to fix all of these parsing errors in your own custom dialect, i can help you with that if you want, we can chat in my slack

https://join.slack.com/t/tobiko-data/shared_invite/zt-1ma66d79v-a4dbf4DUpLAQJ8ptQrJygg

**Comment by joocer** [comment]
Thanks @tobymao I've started to write a custom dialect (mainly cribbed from the postgres dialect) and now the biggest set of parsing issues relate to hints (the WITH clause following relation names).

**Comment by joocer** [comment]
It looks like this may not be feasible to achieve the desired benefit of using it as a SQL rewriter / heuristic optimizer; it appears SQLGlot requires schema information at the Optimization step; however, Opteryx (will) have the schema at the Bind step (which is before its Optimization step) and in ad hoc mode (e.g. CLI querying files) no schema is expected to be available until execution has started.

**Comment by tobymao** [comment]
why can't you just optimize right before execution? you need to understand the schema during execution

**Comment by joocer** [comment]
Hi Toby, that is the current model - I have an existing parser, lexer, binder, planner, optimizer and executor, I would need to refactor the entire stack to use SQLGlot that late in the process. I was investigating inserting it at the front of the existing chain to perform some initial optimization, convert the result back to SQL and pass it through the existing chain, which I've heard referred to as a SQL Rewriter.

For most queries, there's no schema information until the first data file has been read, for example, if you're running a query against a CSV on the command line. This affects what optimizations are possible (e.g. currently only push predicates in single-table queries).

I really like some of the features in your project though and will look to adopt them - the way you've laid out your examples in the README and how the predicate and projection push-downs are pushed to sub-queries - I expect this will be a huge benefit when querying external SQL-aware data sources.

**Comment by joocer** [comment]
Thinking about this and why it's so structurally challenging, it has become clear I've not implemented my planning "correctly". Rather than create a logical plan, I jump straight to creating a physical plan.

If I refactor to separate these activities, replacing the parser to SQLGlot should be (mostly) limited to one/two step in the query engine - the binder and the cost-based analyzer.

I'm splitting out these phases because I think it will simply each step anyway, using SQLGlot may reduce some of the refactoring effort so will be looked at as part of this work.

**Comment by tobymao** [comment]
great!

**Comment by joocer** [comment]
`WITH` statements appear to be supported now.

outstanding issues appear to be:

- `generate_series` with CIDR ranges aren't supported as they only have one parameter - this is non-standard, fix will be to do this expansion in a different function/type. Postgres appears to have an [inet](https://www.postgresql.org/docs/9.3/functions-net.html) type which can be an IP or CIDR
- Interval types (variations of the below)
> SELECT INTERVAL '5 6' YEAR TO MONTH
>❌Invalid expression / Unexpected token. Line 1, Col: 31.

There are other issues, but these appear to be minor bugs

**Comment by joocer** [comment]
INET type added to [SQLGlot](https://github.com/tobymao/sqlglot/pull/1213), now need to refactor code for this case in Opteryx.
